---

    - name: Install apache (httpd)
      yum:
        name: httpd
        state: installed

    - name: Custom index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: enable apache (httpd)
      service:
        name: httpd
        enabled: yes

    - name: Start apache 
      service:
        name: httpd
        state: started

